-- Deploying UDF

select CC_CALL_CENTER_SK,CC_CALL_CENTER_ID ,CC_REC_START_DATE,TO_DATE(CC_REC_START_DATE) + INTERVAL '12 DAY' as "New Date",CC_REC_END_DATE,
CC_CLOSED_DATE_SK from "STUDENTS"."PUBLIC"."CALL_CENTER";


CREATE TABLE CALL_CENTERUDF
AS
select CC_CALL_CENTER_SK,CC_CALL_CENTER_ID ,CC_REC_START_DATE,TO_DATE(CC_REC_START_DATE) + INTERVAL '12 DAY' as "New Date",CC_REC_END_DATE,
CC_CLOSED_DATE_SK from "STUDENTS"."PUBLIC"."CALL_CENTER" LIMIT 1;

CREATE OR REPLACE FUNCTION adding_days(x DATE) 
    returns DATE
    language sql -- this avoid run a subquery over call invokation
    as
    $$
    TO_DATE(X) + INTERVAL '1 YEAR,1DAY'
    $$
    ;
    

select adding_days(CC_REC_START_DATE) FROM "STUDENTS"."PUBLIC"."CALL_CENTER" ;

select CC_CALL_CENTER_SK,CC_CALL_CENTER_ID ,CC_REC_START_DATE,adding_days(CC_REC_START_DATE) AS "New D",CC_REC_END_DATE,
CC_CLOSED_DATE_SK from "STUDENTS"."PUBLIC"."CALL_CENTER" LIMIT 1;


CREATE OR REPLACE TASK mytask
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
   AS
    INSERT INTO CALL_CENTERUDF
    SELECT CC_CALL_CENTER_SK,CC_CALL_CENTER_ID ,CC_REC_START_DATE,adding_days(CC_REC_START_DATE) AS "New D",CC_REC_END_DATE,
    CC_CLOSED_DATE_SK FROM mystream;
    
DESCRIBE TASK mytask;
ALTER TASK mytask RESUME;

SELECT * FROM mystream
    WHERE METADATA$ACTION = 'INSERT';
    
INSERT INTO "PUBLIC"."CALL_CENTER" 
SELECT poc_sequence.nextval, -- sequence
CC_CALL_CENTER_ID,
CC_REC_START_DATE,
CC_REC_END_DATE,
CC_CLOSED_DATE_SK,
CC_OPEN_DATE_SK,
CC_NAME,
CC_CLASS,
CC_EMPLOYEES,
CC_SQ_FT,
CC_HOURS,
CC_MANAGER,
CC_MKT_ID,
CC_MKT_CLASS,
CC_MKT_DESC,
CC_MARKET_MANAGER,
CC_DIVISION,
CC_DIVISION_NAME,
CC_COMPANY,
CC_COMPANY_NAME,
CC_STREET_NUMBER,
CC_STREET_NAME,
CC_STREET_TYPE,
CC_SUITE_NUMBER,
CC_CITY,
CC_COUNTY,
CC_STATE,
CC_ZIP,
CC_COUNTRY,
CC_GMT_OFFSET,
CC_TAX_PERCENTAGE
FROM "STUDENTS"."PUBLIC"."CALL_CENTER" WHERE CC_CALL_CENTER_SK < 5;


SELECT * FROM "STUDENTS"."PUBLIC"."CALL_CENTERUDF";
